# Generated by Django 2.0.3 on 2018-05-22 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180512_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomDataForSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=60)),
                ('blockchain', models.CharField(choices=[('ethereum', 'Ethereum'), ('eos', 'EOS')], max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('data', models.CharField(max_length=32)),
                ('valid_to', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=60)),
                ('blockchain', models.CharField(choices=[('ethereum', 'Ethereum'), ('eos', 'EOS')], max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.AddIndex(
            model_name='randomdataforsign',
            index=models.Index(fields=['identity', 'blockchain'], name='users_rando_identit_7db358_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useridentity',
            unique_together={('identity', 'blockchain')},
        ),
    ]
