# Generated by Django 2.0.3 on 2018-07-20 06:19

import apps.contracts_uis.validators
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=24, unique=True)),
                ('blockchain', models.CharField(choices=[('ethereum', 'Ethereum'), ('eos', 'EOS')], default='ethereum', max_length=50)),
                ('address', models.CharField(default='', max_length=42)),
                ('description', models.TextField()),
                ('functions', django.contrib.postgres.fields.jsonb.JSONField(validators=[apps.contracts_uis.validators.validate_functions])),
                ('sorting_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
