# Generated by Django 2.0.3 on 2018-08-13 09:02

import apps.contracts_uis.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_uis', '0002_auto_20180805_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractui',
            name='dashboard_functions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], validators=[apps.contracts_uis.validators.validate_dashboard_functions]),
        ),
        migrations.AddField(
            model_name='contractui',
            name='function_specs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], validators=[apps.contracts_uis.validators.validate_functions_specs]),
        ),
    ]
