# Generated by Django 2.0.3 on 2018-08-14 19:14

import apps.contracts_uis.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_uis', '0003_auto_20180813_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractui',
            name='function_specs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, validators=[apps.contracts_uis.validators.validate_functions_specs]),
        ),
    ]
