# Generated by Django 2.0.3 on 2018-08-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_uis', '0004_auto_20180814_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractui',
            name='image',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
