# Generated by Django 2.0.3 on 2018-08-15 10:05

import apps.contracts_uis.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_uis', '0005_contractui_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractui',
            name='functions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, validators=[apps.contracts_uis.validators.validate_functions]),
        ),
    ]
