# Generated by Django 2.0.3 on 2018-07-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0005_rename_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dapps', to='constructors.Constructor'),
        ),
    ]
