# Generated by Django 2.0.3 on 2018-08-02 15:48

import apps.dapps.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0007_auto_20180718_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[apps.dapps.validators.validate_log_data]),
        ),
        migrations.AlterField(
            model_name='request',
            name='function_arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[apps.dapps.validators.validate_function_args]),
        ),
        migrations.AlterField(
            model_name='request',
            name='function_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='request',
            name='function_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='function_arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[apps.dapps.validators.validate_function_args]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='function_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='function_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[apps.dapps.validators.validate_tx_info]),
        ),
    ]
