# Generated by Django 2.0.3 on 2018-08-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_uis', '0004_auto_20180814_1914'),
        ('dapps', '0008_auto_20180802_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='dapp',
            name='blockchain',
            field=models.CharField(choices=[('ethereum', 'Ethereum'), ('eos', 'EOS')], default='ethereum', max_length=50),
        ),
        migrations.AddField(
            model_name='dapp',
            name='contract_ui',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dapps', to='contracts_uis.ContractUI'),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='constructor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dapps', to='constructors.Constructor'),
        ),
    ]
