# Generated by Django 2.0.3 on 2018-08-15 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0009_auto_20180814_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapp',
            name='constructor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dapps', to='constructors.Constructor'),
        ),
        migrations.AlterField(
            model_name='dapp',
            name='contract_ui',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dapps', to='contracts_uis.ContractUI'),
        ),
    ]
