# Generated by Django 2.0.3 on 2018-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('payment_address', models.CharField(max_length=42)),
                ('price_eth', models.DecimalField(decimal_places=18, max_digits=30)),
                ('is_public', models.BooleanField(default=False)),
                ('auth0_user_id', models.CharField(max_length=200)),
            ],
        ),
    ]
