# Generated by Django 2.0.3 on 2018-05-18 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='auth0_user_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='constructor',
            name='payment_address',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
