# Generated by Django 2.0.3 on 2018-05-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0002_auto_20180518_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='blockchain',
            field=models.CharField(choices=[('ethereum', 'Ethereum'), ('eos', 'EOS')], default='ethereum', max_length=50),
        ),
        migrations.AddField(
            model_name='constructor',
            name='schema',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='ui_schema',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
