# Generated by Django 2.0.3 on 2018-05-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0002_auto_20180518_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='blockchain',
            field=models.CharField(choices=[('ethereum', 'Ethereum'), ('eos', 'EOS')], default='ethereum', max_length=50),
        ),
    ]
