# Generated by Django 2.0.3 on 2018-06-22 14:36

import apps.constructors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0003_auto_20180531_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='created_at',
            field=models.DateTimeField(default=apps.constructors.models.init_time),
        ),
        migrations.AddField(
            model_name='constructor',
            name='sorting_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructor',
            name='updated_at',
            field=models.DateTimeField(default=apps.constructors.models.init_time),
        ),
    ]
