# Generated by Django 2.0.3 on 2018-07-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructors', '0004_auto_20180622_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructor',
            old_name='price_eth',
            new_name='price',
        ),
    ]
