# Generated by Django 2.0.3 on 2018-05-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=24, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('abi', models.TextField()),
                ('source', models.TextField()),
                ('binary', models.TextField()),
                ('function_specs', models.TextField()),
                ('dashboard_functions', models.TextField()),
                ('has_public_access', models.BooleanField(default=False)),
                ('auth0_user_id', models.CharField(max_length=200)),
                ('network_id', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=42)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructors.Constructor')),
            ],
        ),
    ]
